minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - "@hemilabs/*"
  - "@vetro-protocol/*"
  - "viem-erc20"
  - "viem-erc4626"

packages:
  - "api"
  - "landing"
  - "packages/*"
  - "subgraph"
  - "web"

# https://github.com/microsoft/vscode-eslint/issues/1986#issuecomment-2799868163
publicHoistPattern:
  - "*eslint*"
