export const gatewayAbi = [
  {
    inputs: [],
    name: "PEGGED_TOKEN",
    outputs: [{ type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "token_", type: "address" }],
    name: "mintFee",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "token_", type: "address" }],
    name: "redeemFee",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "treasury",
    outputs: [{ type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawalDelayEnabled",
    outputs: [{ type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawalDelay",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user_", type: "address" }],
    name: "getRedeemRequest",
    outputs: [
      { name: "amountLocked", type: "uint256" },
      { name: "claimableAt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "account_", type: "address" }],
    name: "isInstantRedeemWhitelisted",
    outputs: [{ type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "tokenOut_", type: "address" }],
    name: "maxWithdraw",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "account_", type: "address" }],
    name: "removeFromInstantRedeemWhitelist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "tokenIn_", type: "address" },
      { name: "amountIn_", type: "uint256" },
    ],
    name: "previewDeposit",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "tokenOut_", type: "address" },
      { name: "peggedTokenIn_", type: "uint256" },
    ],
    name: "previewRedeem",
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelRedeemRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "tokenIn_", type: "address" },
      { name: "amountIn_", type: "uint256" },
      { name: "minPeggedTokenOut_", type: "uint256" },
      { name: "receiver_", type: "address" },
    ],
    name: "deposit",
    outputs: [{ type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "tokenOut_", type: "address" },
      { name: "peggedTokenIn_", type: "uint256" },
      { name: "minAmountOut_", type: "uint256" },
      { name: "receiver_", type: "address" },
    ],
    name: "redeem",
    outputs: [{ type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "peggedTokenAmount_", type: "uint256" }],
    name: "requestRedeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "enabled_", type: "bool" }],
    name: "setWithdrawalDelayEnabled",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "token_", type: "address" },
      { name: "newMintFee_", type: "uint256" },
    ],
    name: "updateMintFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "token_", type: "address" },
      { name: "newRedeemFee_", type: "uint256" },
    ],
    name: "updateRedeemFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "newDelay_", type: "uint256" }],
    name: "updateWithdrawalDelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "claimableAt", type: "uint256" },
    ],
    name: "RedeemRequested",
    type: "event",
  },
] as const;
