import { secureHeaders } from "hono/secure-headers";

// Deny all permissions in StandardizedFeatures.
const denyPermissions = [
  "accelerometer",
  "ambientLightSensor",
  "attributionReporting",
  "autoplay",
  "battery",
  "bluetooth",
  "camera",
  "chUa",
  "chUaArch",
  "chUaBitness",
  "chUaFullVersion",
  "chUaFullVersionList",
  "chUaMobile",
  "chUaModel",
  "chUaPlatform",
  "chUaPlatformVersion",
  "chUaWow64",
  "computePressure",
  "crossOriginIsolated",
  "directSockets",
  "displayCapture",
  "encryptedMedia",
  "executionWhileNotRendered",
  "executionWhileOutOfViewport",
  "fullscreen",
  "geolocation",
  "gyroscope",
  "hid",
  "identityCredentialsGet",
  "idleDetection",
  "keyboardMap",
  "magnetometer",
  "microphone",
  "midi",
  "navigationOverride",
  "payment",
  "pictureInPicture",
  "publickeyCredentialsGet",
  "screenWakeLock",
  "serial",
  "storageAccess",
  "syncXhr",
  "usb",
  "webShare",
  "windowManagement",
  "xrSpatialTracking",
];

export const securityHeaders = secureHeaders({
  contentSecurityPolicy: {
    baseUri: ["'none'"],
    defaultSrc: ["'none'"],
    formAction: ["'none'"],
    frameAncestors: ["'none'"],
    requireTrustedTypesFor: ["'script'"],
    sandbox: [],
    upgradeInsecureRequests: [],
  },
  crossOriginEmbedderPolicy: "require-corp",
  crossOriginOpenerPolicy: "same-origin",
  crossOriginResourcePolicy: "same-origin",
  originAgentCluster: true,
  permissionsPolicy: Object.fromEntries(
    denyPermissions.map((feature) => [feature, []]),
  ),
  strictTransportSecurity: false, // Handled by Cloudflare.
});
